"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { createClient } from "@/lib/supabase/client";

// Define the expected shape of our AI-generated sections
interface LessonSection {
  id: string;
  heading: string;
  content: string;
  visualType: string;
  visualDesc: string;
}

interface LessonData {
  id: string;
  title: string;
  description: string;
  content: LessonSection[];
}

export default function LessonPage() {
  const params = useParams();
  const router = useRouter();
  const supabase = createClient();

  const [lesson, setLesson] = useState<LessonData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeSection, setActiveSection] = useState(0);

  // 1. Fetch the data from Supabase
  useEffect(() => {
    const fetchLesson = async () => {
      try {
        // Grab the UUID from the URL
        const lessonId = params.id as string;

        // Fetch the specific lesson row
        const { data, error: dbError } = await supabase
          .from("lessons")
          .select("*")
          .eq("id", lessonId)
          .single();

        if (dbError) throw dbError;
        if (!data) throw new Error("Lesson not found.");

        setLesson({
          id: data.id,
          title: data.title,
          description: data.description,
          content: data.content, // This is the JSON array generated by Gemini
        });
      } catch (err: any) {
        console.error(err);
        setError("Failed to load this module. It may have been deleted or never existed.");
      } finally {
        setIsLoading(false);
      }
    };

    if (params.id) fetchLesson();
  }, [params.id, supabase]);

  // 2. Scroll Spy Effect (Highlights the section you are reading)
  useEffect(() => {
    const handleScroll = () => {
      if (!lesson) return;
      
      const scrollPosition = window.scrollY;
      // Dynamically calculate which section should be active based on scroll depth
      // 400px is roughly the height of one text block
      const calculatedSection = Math.min(
        Math.floor(scrollPosition / 400),
        lesson.content.length - 1
      );
      
      setActiveSection(Math.max(0, calculatedSection));
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, [lesson]);


  // --- RENDER: LOADING STATE ---
  if (isLoading) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center p-8">
        <div className="w-16 h-16 border-4 border-edu-green-pale border-t-edu-green-dark rounded-full animate-spin mb-8"></div>
        <p className="text-edu-olive font-medium animate-pulse">Decrypting module nodes...</p>
      </div>
    );
  }

  // --- RENDER: ERROR STATE ---
  if (error || !lesson) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center p-8 text-center">
        <div className="text-6xl mb-4">🪐</div>
        <h1 className="text-2xl font-bold text-edu-olive mb-2">Lost in space.</h1>
        <p className="text-edu-text mb-8">{error}</p>
        <Link href="/library" className="bg-edu-olive text-white px-6 py-2 rounded-xl font-medium hover:bg-edu-green-dark transition-colors">
          Return to Library
        </Link>
      </div>
    );
  }

  // --- RENDER: SUCCESS STATE (THE SPLIT SCREEN) ---
  return (
    <div className="min-h-screen pt-8 px-4 sm:px-8 pb-32 relative z-10 max-w-7xl mx-auto flex flex-col">
      
      {/* Top Navigation */}
      <nav className="w-full flex justify-between items-center mb-12 border-b border-gray-100 pb-6 sticky top-0 bg-white/80 backdrop-blur-md z-30 pt-4 -mt-4">
        <Link href="/library" className="text-edu-text hover:text-edu-olive transition-colors font-medium flex items-center gap-2">
          <span className="text-xl leading-none mb-0.5">←</span> back to library
        </Link>
        <div className="bg-edu-green-pale text-edu-green-dark px-4 py-1.5 rounded-full text-xs font-bold tracking-wide border border-edu-green/20 uppercase shadow-sm">
          active module
        </div>
      </nav>

      <header className="mb-16 max-w-2xl">
        <motion.h1 
          initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
          className="text-4xl md:text-5xl font-bold text-edu-olive mb-4 tracking-tight"
        >
          {lesson.title}
        </motion.h1>
        <motion.p 
          initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
          className="text-xl text-edu-text font-light leading-relaxed"
        >
          {lesson.description}
        </motion.p>
      </header>

      {/* Split Screen Layout */}
      <div className="flex flex-col lg:flex-row gap-16 relative items-start">
        
        {/* Left Column: The Reading Material */}
        <div className="flex-1 space-y-32 pb-32 lg:w-1/2">
          {lesson.content.map((section, index) => (
            <motion.section 
              key={section.id || index}
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              className={`transition-all duration-700 ${activeSection === index ? 'opacity-100' : 'opacity-30 hover:opacity-100'}`}
            >
              <div className="flex items-center gap-4 mb-6">
                <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm shadow-sm transition-colors ${activeSection === index ? 'bg-edu-olive text-white' : 'bg-gray-100 text-gray-400'}`}>
                  {index + 1}
                </div>
                <h2 className="text-2xl sm:text-3xl font-bold text-edu-olive leading-tight">{section.heading}</h2>
              </div>
              
              {/* Parse basic markdown bolding (e.g., **text**) generated by Gemini */}
              <div 
                className="text-lg text-edu-text leading-relaxed prose prose-p:mb-4 prose-strong:text-edu-olive prose-strong:font-bold"
                dangerouslySetInnerHTML={{ __html: section.content.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }}
              />
              
              {/* Mobile Visual Placeholder (Hidden on Desktop) */}
              <div className="mt-8 lg:hidden bg-[#FFFDF5] rounded-3xl p-8 border border-[#EBE7D9] aspect-square flex flex-col items-center justify-center text-center shadow-inner">
                 <span className="text-edu-green-dark text-4xl mb-4">✦</span>
                 <p className="text-sm text-edu-olive/70 font-medium px-4">{section.visualDesc}</p>
                 <span className="mt-4 text-xs font-bold text-edu-green uppercase tracking-wider">{section.visualType}</span>
              </div>
            </motion.section>
          ))}

          {/* Module Completion CTA */}
          <div className="pt-16 border-t border-gray-100">
            <h3 className="text-3xl font-bold text-edu-olive mb-4">Node complete.</h3>
            <p className="text-lg text-edu-text mb-8 max-w-md">You've successfully mapped this concept. Return to your library to weave your next module.</p>
            <Link href="/library" className="inline-flex items-center justify-center bg-edu-olive text-white px-8 py-4 rounded-xl font-bold hover:bg-edu-green-dark transition-all transform hover:-translate-y-1 shadow-xl">
              Back to Library
            </Link>
          </div>
        </div>

        {/* Right Column: Sticky Visual Container (Desktop Only) */}
        <div className="hidden lg:block lg:w-1/2 sticky top-24">
          <div className="w-full bg-[#FFFDF5] aspect-square rounded-[3rem] shadow-2xl border border-[#EBE7D9] overflow-hidden relative flex flex-col group">
            
            {/* Visual Header */}
            <div className="absolute top-0 w-full p-6 flex justify-between items-center z-10">
              <span className="bg-white/80 backdrop-blur-md text-edu-olive px-4 py-1.5 rounded-full text-xs font-bold tracking-wider uppercase shadow-sm">
                interactive visualizer
              </span>
              <span className="bg-white/80 backdrop-blur-md text-edu-green-dark px-4 py-1.5 rounded-full text-xs font-bold tracking-wider uppercase shadow-sm">
                {lesson.content[activeSection]?.visualType || "Visual"}
              </span>
            </div>

            {/* The Dynamic Generated Visualizer */}
            <div className="flex-1 flex flex-col items-center justify-center p-12 text-center transition-all duration-500 relative overflow-hidden">
              
              {/* Subtle background grid pattern */}
              <div className="absolute inset-0 opacity-10 pointer-events-none" 
                   style={{ backgroundImage: 'linear-gradient(#8BCC3B 1px, transparent 1px), linear-gradient(90deg, #8BCC3B 1px, transparent 1px)', backgroundSize: '20px 20px' }}>
              </div>

              <AnimatePresence mode="wait">
                <motion.div 
                  key={activeSection}
                  initial={{ opacity: 0, scale: 0.9, filter: 'blur(10px)' }}
                  animate={{ opacity: 1, scale: 1, filter: 'blur(0px)' }}
                  exit={{ opacity: 0, scale: 1.1, filter: 'blur(10px)' }}
                  transition={{ duration: 0.4 }}
                  className="flex flex-col items-center relative z-10"
                >
                  <div className="w-32 h-32 mb-8 text-edu-green-dark flex justify-center items-center relative">
                    {/* Abstract shapes that rotate/change based on the section index to simulate dynamic visuals */}
                    <motion.div 
                      animate={{ rotate: 360 }} 
                      transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
                      className={`absolute inset-0 border-4 border-dashed rounded-full border-edu-green-dark/30`}
                    />
                    <div className="text-5xl">
                      {lesson.content[activeSection]?.visualType === "diagram" ? "📐" : 
                       lesson.content[activeSection]?.visualType === "animation" ? "🎬" : 
                       lesson.content[activeSection]?.visualType === "chart" ? "📊" : "🧠"}
                    </div>
                  </div>
                  
                  <h3 className="text-2xl font-bold text-edu-olive mb-4">
                    {lesson.content[activeSection]?.heading}
                  </h3>
                  
                  {/* The AI's exact visual instructions */}
                  <p className="text-edu-text font-medium text-lg max-w-sm leading-relaxed bg-white/60 p-6 rounded-2xl shadow-sm border border-white">
                    {lesson.content[activeSection]?.visualDesc}
                  </p>
                </motion.div>
              </AnimatePresence>
            </div>

          </div>
        </div>

      </div>
    </div>
  );
}